#-------------------------------
# Site Settings
title: Cogniteo
description: Cogniteo - an Independent Platform Engineering Collective 
logo: /images/icononly_transparent_nobuffer.png
logo_dark: /images/icononly_transparent_nobuffer.png


#-------------------------------
# Color Scheme Settings
color_scheme:
  default: dark # Default theme applied on the first visit (options: "light" or "dark")
  toggle: true # Enable theme toggle

# Enables or disables the theme toggle functionality:
# - true: Users can switch between light and dark modes using a toggle button.
#          The site will remember their choice for future visits.
# - false: The theme will always use the default mode specified above,
#          and the toggle button will not be displayed.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: "Services"
      url: '/services/'
    - title: 'Platforms'
      url: '/platforms/'
    - title: 'Comparison'
      url: '/comparison/'
    - title: 'Community'
      url: '/community/'
    - title: 'Events'
      url: '/events/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Pages'
      submenu:
      - title: 'DNA'
        url: '/dna/'
      - title: 'Team'
        url: '/team/'
      - title: 'Partners'
        url: '/partners/'


#-------------------------------
# Author Settings
author:
  author_name: Piotr Szwed
  author_avatar: /images/01-1.jpg


#-------------------------------
# Hero Settings
hero:
  enable: true
#  hero_avatar: /images/01-1.jpg
  hero_title: AI-Native Platforms
  hero_subtitle: <b>Intent-Driven Autonomous Infrastructure.</b><br>

    We’re a team of battle-hardened engineers who have seen things… terrifying YAML files, rogue Terraform scripts, and Kubernetes clusters held together by sheer willpower. But fear not! We specialize in <b>AI-Native Platforms</b> – helping teams build self-service, scalable, and headache-free Developer experiences.

    Less toil, more flow. More speed, less Ops. And definitely no more “it works on my machine” excuses.

  hero_image: /images/fulllogo.png
  hero_image_caption: Let’s build something amazing – without the duct tape.
  hero_button_text: Contact us
  hero_button_link: '/contact/'


# Logos
logos:
  enable: true
  logos_title: Happy Customers
  logo_image:
    - alt: "Shell"
      image: "/images/logo/shell.jpeg"
    - alt: "Grundfos"
      image: "/images/logo/grundfos.jpeg"
    - alt: "Activision & Blizzard"
      image: "/images/logo/activision.jpeg"
    - alt: "Barco"
      image: "/images/logo/barco.jpeg"
    - alt: "Philips"
      image: "/images/logo/philips.jpeg"
    - alt: "Intel"
      image: "/images/logo/intel.jpeg"
    - alt: "SLB"
      image: "/images/logo/slb.jpeg"
    - alt: "Sony"
      image: "/images/logo/sony.jpeg"



#-------------------------------
# Section Blog Settings
#blog:
#  enable: true
#  blog_title: The Binary Journal


#-------------------------------
# Tags Section Settings
#tags_section:
#  enable: true
#  tags_section_title: Hacker’s Haven
#  tags:
#    - tag: "Programming"
#      image: "/images/20.jpg"
#    - tag: "Linux"
#      image: "/images/21.jpg"
#    - tag: "Productivity"
#      image: "/images/22.jpg"
#    - tag: "Security"
#      image: "/images/23.jpg"


#-------------------------------
# Videos Section Settings
#videos_section:
#  enable: true
#  videos_section_title: Latest Videos


#-------------------------------
# Gallery Section Settings
#gallery_section:
#  enable: true
#  gallery_section_title: Byte Frame
#  gallery:
#    gallery_images:
#      - alt: 'Rest'
#        url: '/images/100.jpg'
#        caption: 'Small steps lead to big results.'
#      - alt: 'Lifestyle'
#        url: '/images/101.jpg'
#        caption: 'A peaceful moment captured during a serene evening.'
#      - alt: 'Hobby'
#        url: '/images/102.jpg'
#        caption: 'True friends are like stars — they shine brightest when the world feels dark.'
#      - alt: 'Computers'
#        url: '/images/103.jpg'
#        caption: 'Every click opens a new chapter in an endless story.'
#      - alt: 'Games'
#        url: '/images/104.jpg'
#        caption: 'Every level is a new opportunity to test your limits.'


#-------------------------------
# Newsletter Settings
#mailchimp:
#  enable: true
#  mailchimp_title: Stay inspired weekly ✌️
#  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
#  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
#  mailchimp_input_text: Your email address...
#  mailchimp_button_text: Join Now


#-------------------------------
# Footer Settings
#footer_description: Here, I share ideas, tools, and methods that help me balance productivity with creativity while keeping control over my digital world. Dive in, get inspired, and feel free to share your thoughts!


#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-x-twitter", name: "X", link: "https://x.com/cogniteo"}
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/company/cogniteo"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/orgs/Cogniteo/repositories"}
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://www.youtube.com/@ai-native-platforms"}
- {icon: "fa-brands fa-slack", name: "Slack", link: "https://cloud-native.slack.com/#platform-engineering"}
- {icon: "fa-solid fa-rss", name: "Rss", link: "/feed.xml"}

# Example of adding a new link to the sidebar and footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: xeoebpky # Add your form_id
  button_text: Send Now

# NOTE
# Coderon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Google Analytics
google_analytics: G-VKYMWH3QH4
